//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SneackApp.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class pupils
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pupils()
        {
            this.sneackers = new HashSet<sneackers>();
        }
    
        public int pupil_id { get; set; }
        public string FIO { get; set; }
        public string Sex { get; set; }
        public System.DateTime Birhdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sneackers> sneackers { get; set; }
    }
}
